server:
  port: 8080
app:
  name: sco-createpromo-adapter
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
mapping:
  hostname: http://localhost:8080
  rubbles-post: /rubbles
  sco-post: /createpromo
db:
  sql:
    update-rb-promo-acrm-sco: UPDATE RB_PROMO_ACRM_SCO SET SCO_UPLOAD_FLG = 1 WHERE PROMO_ID IN (:promo_id);
  tables:
    rb-promo-acrm-sco: RB_PROMO_ACRM_SCO
    rb-item-groups: RB_ITEM_GROUPS
    rb-pos-groups: RB_POS_GROUPS
    int-rb-item-list: INT_RB_ITEM_LIST
    int-post-of-sales-rb: INT_POINT_OF_SALES_RB
  postgres:
    batch_size: 8
    batch_timeout_ms: 1000
    cdm:
      url: jdbc:postgresql://127.0.0.1:5432/a366?reWriteBatchedInserts=true
      username: postgres
      password: pHzRcr9Bp70%3D
      hikari:
        pool-name: postgres-pool-cdm
        minimum-idle: 0
        maximum-pool-size: 1
    int:
      url: jdbc:postgresql://127.0.0.1:5432/a366?reWriteBatchedInserts=true
      username: postgres
      password: pHzRcr9Bp70%3D
      hikari:
        pool-name: postgres-pool-int
        minimum-idle: 0
        maximum-pool-size: 1

sftp:
  host: 192.168.56.101
  username: java
  password: 9n1b97QvqG8RA1YZdlKLJQ%3D%3D
sco:
  retry_count: 2
  retry_timeout_sec: 1
files:
  local:
    #относительный путь
    directory:
    archive-directory: archive/
  remote:
    directory: /upload/
  remove-success-files: true